// <auto-generated />
using System;
using FifthBot.Resources.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FifthBot.Migrations
{
    [DbContext(typeof(SqliteDbContext))]
    [Migration("20190811065231_cleanstart")]
    partial class cleanstart
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028");

            modelBuilder.Entity("FifthBot.Resources.Database.Attack", b =>
                {
                    b.Property<ulong>("MessageID")
                        .ValueGeneratedOnAdd();

                    b.Property<ulong>("AttackerId");

                    b.Property<string>("Category");

                    b.Property<DateTime>("DateandTime");

                    b.Property<string>("Name");

                    b.Property<ulong>("TargetId");

                    b.HasKey("MessageID");

                    b.ToTable("Attacks");
                });

            modelBuilder.Entity("FifthBot.Resources.Database.Command", b =>
                {
                    b.Property<ulong>("MsgID")
                        .ValueGeneratedOnAdd();

                    b.Property<ulong>("ActorID");

                    b.Property<DateTime>("DateTime");

                    b.Property<string>("Name");

                    b.Property<ulong>("TargetID");

                    b.HasKey("MsgID");

                    b.ToTable("Commands");
                });

            modelBuilder.Entity("FifthBot.Resources.Database.IntroChannel", b =>
                {
                    b.Property<ulong>("ChannelID")
                        .ValueGeneratedOnAdd();

                    b.Property<ulong>("ServerID");

                    b.HasKey("ChannelID");

                    b.ToTable("IntroChannels");
                });

            modelBuilder.Entity("FifthBot.Resources.Database.ServerSetting", b =>
                {
                    b.Property<ulong>("ServerID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ServerName");

                    b.HasKey("ServerID");

                    b.ToTable("ServerSettings");
                });

            modelBuilder.Entity("FifthBot.Resources.Database.Stone", b =>
                {
                    b.Property<ulong>("UserId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Amount");

                    b.HasKey("UserId");

                    b.ToTable("Stones");
                });
#pragma warning restore 612, 618
        }
    }
}
